
server:
  port: 8080

spring:
  datasource:
    username: root
    password: Abc@#123
    url: jdbc:mysql://49.234.89.231:3306/QuestionAnswerSystem?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 49.234.89.231
    port: 6379
    password: Abc123
    connect-timeout: 5000


mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug

